import 'package:flutter/material.dart';
import '../../app_theme.dart';

enum AppThemes {
  DEFAULT,
  SANDRED,
  MEDNIGHT;

  static AppThemes from(String type) =>
      AppThemes.values.firstWhere((e) => e.name == type);

  AppTheme get appTheme {
    switch (this) {
      case AppThemes.SANDRED:
        return _AppThemeCollection.SANDRED;
      case AppThemes.MEDNIGHT:
        return _AppThemeCollection.MEDNIGHT;
      default:
        return _AppThemeCollection.DEFAULT;
    }
  }
}

abstract class _AppThemeCollection {
  static AppTheme get DEFAULT => const AppTheme(
        dark: AppThemeData(
          colorScheme: AppColorScheme(
            brightness: Brightness.dark,
            primary: Color(0xFFAEC6FF),
            onPrimary: Color(0xFF002E6B),
            primaryContainer: Color(0xFF13448F),
            onPrimaryContainer: Color(0xFFD8E2FF),
            secondary: Color(0xFFA0CAFF),
            onSecondary: Color(0xFF003259),
            secondaryContainer: Color(0xFF00497E),
            onSecondaryContainer: Color(0xFFD2E4FF),
            tertiary: Color(0xFFAEC6FF),
            onTertiary: Color(0xFF002E6B),
            tertiaryContainer: Color(0xFF13448F),
            onTertiaryContainer: Color(0xFFD8E2FF),
            error: Color(0xFFFFB4AB),
            errorContainer: Color(0xFF93000A),
            onError: Color(0xFF690005),
            onErrorContainer: Color(0xFFFFDAD6),
            background: Color(0xFF1B1B1F),
            onBackground: Color(0xFFE3E2E6),
            surface: Color(0xFF1B1B1F),
            onSurface: Color(0xFFE3E2E6),
            surfaceVariant: Color(0xFF44474F),
            onSurfaceVariant: Color(0xFFC5C6D0),
            outline: Color(0xFF8E9099),
            onInverseSurface: Color(0xFF1B1B1F),
            inverseSurface: Color(0xFFE3E2E6),
            inversePrimary: Color(0xFF335CA8),
            shadow: Color(0xFF000000),
            surfaceTint: Color(0xFFAEC6FF),
            outlineVariant: Color(0xFF44474F),
            scrim: Color(0xFF000000),
            icon: Color(0xFF90A2B4),
            primaryUserMessageCard: Color(0xFF505962),
            clientMessageCard: Color(0xFF292A2E),
            clientText: Color(0xFFF9FAFC),
            primaryUserText: Color(0xFFF9FAFC),
            clientCaption: Colors.white54,
            primaryUserCaption: Colors.white54,
            primeryText: Color(0xFFF9FAFC),
            secondaryText: Colors.white38,
          ),
        ),
        light: AppThemeData(
          colorScheme: AppColorScheme(
            brightness: Brightness.light,
            primary: Color(0xFF335CA8),
            onPrimary: Color(0xFFFFFFFF),
            primaryContainer: Color(0xFFD8E2FF),
            onPrimaryContainer: Color(0xFF001A42),
            secondary: Color(0xFF0961A4),
            onSecondary: Color(0xFFFFFFFF),
            secondaryContainer: Color(0xFFD2E4FF),
            onSecondaryContainer: Color(0xFF001C37),
            tertiary: Color(0xFF335CA8),
            onTertiary: Color(0xFFFFFFFF),
            tertiaryContainer: Color(0xFFD8E2FF),
            onTertiaryContainer: Color(0xFF001A42),
            error: Color(0xFFBA1A1A),
            errorContainer: Color(0xFFFFDAD6),
            onError: Color(0xFFFFFFFF),
            onErrorContainer: Color(0xFF410002),
            background: Color(0xFFFEFBFF),
            onBackground: Color(0xFF1B1B1F),
            surface: Color(0xFFFEFBFF),
            onSurface: Color(0xFF1B1B1F),
            surfaceVariant: Color(0xFFE1E2EC),
            onSurfaceVariant: Color(0xFF44474F),
            outline: Color(0xFF757780),
            onInverseSurface: Color(0xFFF2F0F4),
            inverseSurface: Color(0xFF303034),
            inversePrimary: Color(0xFFAEC6FF),
            shadow: Color(0xFF000000),
            surfaceTint: Color(0xFF335CA8),
            outlineVariant: Color(0xFFC5C6D0),
            scrim: Color(0xFF000000),
            icon: Color(0xff53A1EB),
            primaryUserMessageCard: Color(0xff52A2E9),
            clientMessageCard: Color(0xffF0F0F0),
            clientText: Colors.black,
            primaryUserText: Color(0xffF9FAFC),
            clientCaption: Colors.black54,
            primaryUserCaption: Colors.white54,
            primeryText: Colors.black,
            secondaryText: Colors.black45,
          ),
        ),
      );

  static AppTheme get SANDRED => const AppTheme(
      light: AppThemeData(
          colorScheme: AppColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF8F4E00),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFFFDCC2),
        onPrimaryContainer: Color(0xFF2E1500),
        secondary: Color(0xFF895200),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFFFDCBC),
        onSecondaryContainer: Color(0xFF2C1700),
        tertiary: Color(0xFF825500),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFFFDDB3),
        onTertiaryContainer: Color(0xFF291800),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFFFFBFF),
        onBackground: Color(0xFF201B17),
        surface: Color(0xFFFFFBFF),
        onSurface: Color(0xFF201B17),
        surfaceVariant: Color(0xFFF3DFD1),
        onSurfaceVariant: Color(0xFF51443B),
        outline: Color(0xFF847469),
        onInverseSurface: Color(0xFFFAEEE8),
        inverseSurface: Color(0xFF352F2B),
        inversePrimary: Color(0xFFFFB77B),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF8F4E00),
        outlineVariant: Color(0xFFD6C3B6),
        scrim: Color(0xFF000000),
        clientCaption: Color(0xFFD6C3B6),
        clientMessageCard: Color(0xFFFFDCBC),
        clientText: Color(0xFF201B17),
        icon: Color(0xFF201B17),
        primaryUserCaption: Color(0xFF201B17),
        primaryUserMessageCard: Color(0xFF895200),
        primaryUserText: Color(0xFF201B17),
        primeryText: Color(0xFF8F4E00),
        secondaryText: Color(0xFF201B17),
      )),
      dark: AppThemeData(
          colorScheme: AppColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFFFFB77B),
        onPrimary: Color(0xFF4C2700),
        primaryContainer: Color(0xFF6D3A00),
        onPrimaryContainer: Color(0xFFFFDCC2),
        secondary: Color(0xFFFFB86A),
        onSecondary: Color(0xFF492900),
        secondaryContainer: Color(0xFF683D00),
        onSecondaryContainer: Color(0xFFFFDCBC),
        tertiary: Color(0xFFFFB950),
        onTertiary: Color(0xFF452B00),
        tertiaryContainer: Color(0xFF633F00),
        onTertiaryContainer: Color(0xFFFFDDB3),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF201B17),
        onBackground: Color(0xFFECE0DA),
        surface: Color(0xFF201B17),
        onSurface: Color(0xFFECE0DA),
        surfaceVariant: Color(0xFF51443B),
        onSurfaceVariant: Color(0xFFD6C3B6),
        outline: Color(0xFF9E8E82),
        onInverseSurface: Color(0xFF201B17),
        inverseSurface: Color(0xFFECE0DA),
        inversePrimary: Color(0xFF8F4E00),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFFFFB77B),
        outlineVariant: Color(0xFF51443B),
        scrim: Color(0xFF000000),
        clientCaption: Color(0xFFECE0DA),
        clientMessageCard: Color(0xFF452B00),
        clientText: Color(0xFFECE0DA),
        icon: Color(0xFF9E8E82),
        primaryUserCaption: Color(0xFFECE0DA),
        primaryUserMessageCard: Color(0xFF452B00),
        primaryUserText: Color(0xFFECE0DA),
        primeryText: Color(0xFFECE0DA),
        secondaryText: Color(0xFFECE0DA),
      )));

  static AppTheme get MEDNIGHT => const AppTheme(
      dark: AppThemeData(
          colorScheme: AppColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFFD2BBFF),
        onPrimary: Color(0xFF3B1D71),
        primaryContainer: Color(0xFF523689),
        onPrimaryContainer: Color(0xFFEADDFF),
        secondary: Color(0xFFFFB1C8),
        onSecondary: Color(0xFF5E1133),
        secondaryContainer: Color(0xFF7B2949),
        onSecondaryContainer: Color(0xFFFFD9E2),
        tertiary: Color(0xFFC7BFFF),
        onTertiary: Color(0xFF2D2276),
        tertiaryContainer: Color(0xFF443A8E),
        onTertiaryContainer: Color(0xFFE4DFFF),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF1D1B1E),
        onBackground: Color(0xFFE6E1E6),
        surface: Color(0xFF1D1B1E),
        onSurface: Color(0xFFE6E1E6),
        surfaceVariant: Color(0xFF49454E),
        onSurfaceVariant: Color(0xFFCBC4CF),
        outline: Color(0xFF948F99),
        onInverseSurface: Color(0xFF1D1B1E),
        inverseSurface: Color(0xFFE6E1E6),
        inversePrimary: Color(0xFF6A4FA3),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFFD2BBFF),
        outlineVariant: Color(0xFF49454E),
        scrim: Color(0xFF000000),
        clientCaption: Color(0xFFFFD9E2),
        clientMessageCard: Color(0xFF7B2949),
        clientText: Color(0xFFFFD9E2),
        icon: Color(0xFF201B17),
        primaryUserCaption: Color(0xFF3B1D71),
        primaryUserMessageCard: Color(0xFFD2BBFF),
        primaryUserText: Color(0xFF3B1D71),
        primeryText: Color(0xFF3B1D71),
        secondaryText: Color(0xFFFFD9E2),
      )),
      light: AppThemeData(
          colorScheme: AppColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF6A4FA3),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFEADDFF),
        onPrimaryContainer: Color(0xFF25005A),
        secondary: Color(0xFF984061),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFFFD9E2),
        onSecondaryContainer: Color(0xFF3E001D),
        tertiary: Color(0xFF5C53A7),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFE4DFFF),
        onTertiaryContainer: Color(0xFF170362),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFFFFBFF),
        onBackground: Color(0xFF1D1B1E),
        surface: Color(0xFFFFFBFF),
        onSurface: Color(0xFF1D1B1E),
        surfaceVariant: Color(0xFFE7E0EB),
        onSurfaceVariant: Color(0xFF49454E),
        outline: Color(0xFF7A757F),
        onInverseSurface: Color(0xFFF5EFF4),
        inverseSurface: Color(0xFF323033),
        inversePrimary: Color(0xFFD2BBFF),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF6A4FA3),
        outlineVariant: Color(0xFFCBC4CF),
        scrim: Color(0xFF000000),
        clientCaption: Color(0xFFFFFFFF),
        clientMessageCard: Color(0xFF984061),
        clientText: Color(0xFFFFFFFF),
        icon: Color(0xFF7A757F),
        primaryUserCaption: Color(0xFF25005A),
        primaryUserMessageCard: Color(0xFFD2BBFF),
        primaryUserText: Color(0xFF25005A),
        primeryText: Color(0xFF25005A),
        secondaryText: Color(0xFF25005A),
      )));
}
