name: reConnect
description: Get ready to reConnect like never before with reConnect! This
  friendly chat app, built with Flutter, is here to bring people together.
  Available on web, mobile, and Windows, reConnect ensures a smooth and
  consistent experience across all devices. Stay connected with loved ones,
  catch up with friends, and make new connections effortlessly. With its
  user-friendly interface and powerful features, reConnect makes chatting a
  breeze. Share moments, engage in meaningful conversations, and enjoy group
  discussions with ease. Download reConnect today and experience the joy of
  connecting in a fun and friendly way!

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  logs:
    git:
      url: https://github.com/rahulsharmadev-community/logs.git
      ref: v0.0.1
    
  android_info:
    git: https://github.com/rahulsharmadev-community/android_info.git

  cached_image:
    git: 
      url: https://github.com/rahulsharmadev-community/cached_image.git
      ref: v0.0.1

  dio: ^5.3.0
  bloc: ^8.1.2
  
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.1
  firebase_messaging: ^14.6.3
  image_size_getter: ^2.1.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  file_picker: ^5.3.3
  camera: ^0.10.5+2
  go_router: ^8.0.5


  meta: ^1.9.1
  uuid: ^3.0.7
  crypto: ^3.0.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  shared:
    path: ../../shared/

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
