name: reConnect
description: Get ready to reConnect like never before with reConnect! This friendly chat app, built with Flutter, is here to bring people together. Available on web, mobile, and Windows, reConnect ensures a smooth and consistent experience across all devices. Stay connected with loved ones, catch up with friends, and make new connections effortlessly. With its user-friendly interface and powerful features, reConnect makes chatting a breeze. Share moments, engage in meaningful conversations, and enjoy group discussions with ease. Download reConnect today and experience the joy of connecting in a fun and friendly way!
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Media Services
  http: ^0.13.0
  image_picker: ^0.8.9
  video_player: ^2.6.1

  # Necessary Packages
  go_router: ^8.0.5
  equatable: ^2.0.5
  bloc_test: ^9.1.3
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1
  path_provider: ^2.0.15
  device_info_plus: ^9.0.2
  permission_handler: ^10.3.0

  android_info:
    git: https://github.com/rahulsharmadev-community/android_info.git

  # Google Firebase Services
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.6.3

  shared:
    path: ../../shared/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.1.1

flutter:
  uses-material-design: true
