name: shared
description: Common data models required by our client and server
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  uuid: ^3.0.7

  # Google Firebase Services
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  firebase_messaging: ^14.6.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
