name: shared
description: Common data models required by our client and server
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.7
  crypto: ^3.0.3
  meta: ^1.9.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  equatable: ^2.0.5
  collection: ^1.17.1
  image_size_getter: ^2.1.2
  http: ^1.1.0
  rxdart: ^0.27.7
  # Google Firebase Services
  googleapis_auth: ^1.4.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.3
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5

  logs:
    git:
      url: https://github.com/rahulsharmadev-community/logs.git
      ref: v0.0.1
      
  jars:
    git: 
      url: https://github.com/rahulsharmadev-community/jars.git
      ref: v0.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
