import 'package:flutter/material.dart';
import 'app_theme.dart';

class AppThemesCollection {
  AppThemesCollection._();
  static final Map<String, AppTheme> theme = {
    'DEFAULT': const AppTheme(
      dark: AppThemeData(
        colorScheme: AppColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xFFAEC6FF),
          onPrimary: Color(0xFF002E6B),
          primaryContainer: Color(0xFF13448F),
          onPrimaryContainer: Color(0xFFD8E2FF),
          secondary: Color(0xFFA0CAFF),
          onSecondary: Color(0xFF003259),
          secondaryContainer: Color(0xFF00497E),
          onSecondaryContainer: Color(0xFFD2E4FF),
          tertiary: Color(0xFFAEC6FF),
          onTertiary: Color(0xFF002E6B),
          tertiaryContainer: Color(0xFF13448F),
          onTertiaryContainer: Color(0xFFD8E2FF),
          error: Color(0xFFFFB4AB),
          errorContainer: Color(0xFF93000A),
          onError: Color(0xFF690005),
          onErrorContainer: Color(0xFFFFDAD6),
          background: Color(0xFF1B1B1F),
          onBackground: Color(0xFFE3E2E6),
          surface: Color(0xFF1B1B1F),
          onSurface: Color(0xFFE3E2E6),
          surfaceVariant: Color(0xFF44474F),
          onSurfaceVariant: Color(0xFFC5C6D0),
          outline: Color(0xFF8E9099),
          onInverseSurface: Color(0xFF1B1B1F),
          inverseSurface: Color(0xFFE3E2E6),
          inversePrimary: Color(0xFF335CA8),
          shadow: Color(0xFF000000),
          surfaceTint: Color(0xFFAEC6FF),
          outlineVariant: Color(0xFF44474F),
          scrim: Color(0xFF000000),
          icon: Color(0xFF90A2B4),
          primaryUserMessageCard: Color(0xFF505962),
          clientMessageCard: Color(0xFF292A2E),
          clientText: Color(0xFFF9FAFC),
          primaryUserText: Color(0xFFF9FAFC),
          clientCaption: Colors.white54,
          primaryUserCaption: Colors.white54,
          primeryText: Color(0xFFF9FAFC),
          secondaryText: Colors.white38,
        ),
      ),
      light: AppThemeData(
        colorScheme: AppColorScheme(
          brightness: Brightness.light,
          primary: Color(0xFF335CA8),
          onPrimary: Color(0xFFFFFFFF),
          primaryContainer: Color(0xFFD8E2FF),
          onPrimaryContainer: Color(0xFF001A42),
          secondary: Color(0xFF0961A4),
          onSecondary: Color(0xFFFFFFFF),
          secondaryContainer: Color(0xFFD2E4FF),
          onSecondaryContainer: Color(0xFF001C37),
          tertiary: Color(0xFF335CA8),
          onTertiary: Color(0xFFFFFFFF),
          tertiaryContainer: Color(0xFFD8E2FF),
          onTertiaryContainer: Color(0xFF001A42),
          error: Color(0xFFBA1A1A),
          errorContainer: Color(0xFFFFDAD6),
          onError: Color(0xFFFFFFFF),
          onErrorContainer: Color(0xFF410002),
          background: Color(0xFFFEFBFF),
          onBackground: Color(0xFF1B1B1F),
          surface: Color(0xFFFEFBFF),
          onSurface: Color(0xFF1B1B1F),
          surfaceVariant: Color(0xFFE1E2EC),
          onSurfaceVariant: Color(0xFF44474F),
          outline: Color(0xFF757780),
          onInverseSurface: Color(0xFFF2F0F4),
          inverseSurface: Color(0xFF303034),
          inversePrimary: Color(0xFFAEC6FF),
          shadow: Color(0xFF000000),
          surfaceTint: Color(0xFF335CA8),
          outlineVariant: Color(0xFFC5C6D0),
          scrim: Color(0xFF000000),
          icon: Color(0xff53A1EB),
          primaryUserMessageCard: Color(0xff52A2E9),
          clientMessageCard: Color(0xffF0F0F0),
          clientText: Colors.black,
          primaryUserText: Color(0xffF9FAFC),
          clientCaption: Colors.black54,
          primaryUserCaption: Colors.white54,
          primeryText: Colors.black,
          secondaryText: Colors.black45,
        ),
      ),
    )
  };
}
